name: Release WildFly gRPC

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    name: Deploy Maven Artifacts
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: $MVN install
      - uses: actions/setup-java@v4
        with: # running setup-java again overwrites the settings.xml
          java-version: 17
          distribution: temurin
          server-id: jboss
          server-username: NEXUS3_USERNAME
          server-password: NEXUS3_PASSWORD
          gpg-private-key: ${{ secrets.MAVEN_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      - run: $MVN deploy -P jboss-release -pl '!testsuite,!testsuite/integration,!testsuite/integration/subsystem'
        env:
          NEXUS3_USERNAME: ${{ secrets.NEXUS3_USERNAME }}
          NEXUS3_PASSWORD: ${{ secrets.NEXUS3_PASSWORD }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.MAVEN_GPG_PASSPHRASE }}

  release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - id: get-version
        uses: battila7/get-version-action@v2.3.0
      - uses: actions/checkout@v5
      - id: read-changelog
        uses: mindsers/changelog-reader-action@v2
        with:
          path: ./CHANGELOG.md
          version: ${{ steps.get-version.outputs.version-without-v }}
      - uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get-version.outputs.version }}
          release_name: WildFly gRPC ${{ steps.get-version.outputs.version-without-v }}
          body: ${{ steps.read-changelog.outputs.changes }}
          draft: false
          prerelease: false
