name: Verify Codebase

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Verify Codebase
    runs-on: ubuntu-latest
    env:
      MVN: ./mvnw --show-version --batch-mode
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: $MVN install -Pexamples

  format-check:
    name: Check Code Formatting
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: temurin
          cache: maven
      - run: $MVN clean install -DskipTests formatter:format -Pexamples
      - run:  |
          [ -z "$(git status --porcelain=v1 2>/dev/null)" ] || (echo -e "::error ::Changes have been found\n$(git diff)" && exit 1)
